version: '3'
services:
  app:
    build: .docker
    container_name: felicio
    volumes:
      - .:/var/www/app
      - ".docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    tty: true
